fix: telemetry logger
currently if you have a run yaml without telemetry the following error is hit:

TypeError: TelemetryAdapter.__init__() missing 1 required positional argument: 'deps'

this is because the TelemetryAdapter requires a deps arg to be passed. Pass {} to avoid errors.

Signed-off-by: Charlie Doern <cdoern@redhat.com>