fix(test): increase event loop timeout
The test is failing because the synchronous HTTP server in
MockInferenceAdapterWithSleep is blocking the event loop for
longer than the configured slow_callback_duration of 0.1
seconds on GitHub actions.

```
=================================== FAILURES ===================================
_________________ test_chat_completion_doesnt_block_event_loop _________________

caplog = <_pytest.logging.LogCaptureFixture object at 0x7f016eb918a0>

    def test_chat_completion_doesnt_block_event_loop(caplog):
        loop = asyncio.new_event_loop()
        loop.set_debug(True)
        caplog.set_level(logging.WARNING)

        # Log when event loop is blocked for more than 100ms
        loop.slow_callback_duration = 0.1
        # Sleep for 500ms in our delayed http response
        sleep_time = 0.5

        mock_model = Model(identifier="mock-model", provider_resource_id="mock-model", provider_id="vllm-inference")
        mock_response = {
            "id": "chatcmpl-abc123",
            "object": "chat.completion",
            "created": 1,
            "modle": "mock-model",
            "choices": [
                {
                    "message": {"content": ""},
                    "logprobs": None,
                    "finish_reason": "stop",
                    "index": 0,
                }
            ],
        }

        async def do_chat_completion():
            await inference_adapter.chat_completion(
                "mock-model",
                [],
                stream=False,
                tools=None,
                tool_config=ToolConfig(tool_choice=ToolChoice.auto),
            )

        with MockInferenceAdapterWithSleep(sleep_time, mock_response) as inference_adapter:
            inference_adapter.model_store = AsyncMock()
            inference_adapter.model_store.get_model.return_value = mock_model
            loop.run_until_complete(inference_adapter.initialize())

            # Clear the logs so far and run the actual chat completion we care about
            caplog.clear()
            loop.run_until_complete(do_chat_completion())

        # Ensure we don't have any asyncio warnings in the captured log
        # records from our chat completion call. A message gets logged
        # here any time we exceed the slow_callback_duration configured
        # above.
        asyncio_warnings = [record.message for record in caplog.records if record.name == "asyncio"]
>       assert not asyncio_warnings
E       assert not ["Executing <Task pending name='Task-63' coro=<test_chat_completion_doesnt_block_event_loop.<locals>.do_chat_completion() running at /home/runner/work/llama-stack/llama-stack/tests/unit/providers/inference/test_remote_vllm.py:212> cb=[_run_until_complete_cb() at /opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/asyncio/base_events.py:184] created at /opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/asyncio/tasks.py:636> took 0.144 seconds"]
```

Signed-off-by: Sébastien Han <seb@redhat.com>